### ISSUE TITLE
Dependencies were not found:  * !!vue-style-loader

### ISSUE THREAD

**Issue by pateash** [vuejs/vue-style-loader#12]
**I am getting following error on running dev **server****,

 **i was not facing this problem just moments ago, i tried deleting npm cache, even deleting whole node_modules folder and then reinstalling, any suggestion???**

`/usr/bin/node /usr/lib/nodejs/npm/bin/npm-cli.js run dev --scripts-prepend-node-path=auto

> portfolio@1.0.0 dev /home/ashish/Desktop/portfolio
> node build/dev-server.js

> Starting dev server...
 ERROR  Failed to compile with 11 errors23:20:02

These dependencies were not found:

* !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-3df80271","scoped":false,"hasInlineConfig":false}!../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./App.vue in ./src/App.vue
* !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-33ec801b","scoped":false,"hasInlineConfig":false}!../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./apnav.vue in ./src/components/apnav.vue
* !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-4d55f832","scoped":false,"hasInlineConfig":false}!../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./contact.vue in ./src/components/contact.vue
* !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-40cc66c3","scoped":false,"hasInlineConfig":false}!../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./projects.vue in ./src/components/projects.vue
* !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-15ef8928","scoped":false,"hasInlineConfig":false}!../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./home.vue in ./src/components/home.vue
* !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-246589fe","scoped":false,"hasInlineConfig":false}!../../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./kisanmitra.vue in ./src/components/projects/kisanmitra.vue
* !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-12704844","scoped":false,"hasInlineConfig":false}!../../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./bigquery.vue in ./src/components/projects/bigquery.vue
* !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-26460aa9","scoped":false,"hasInlineConfig":false}!../../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./manitmoodle.vue in ./src/components/projects/manitmoodle.vue
* !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-6b0a1dae","scoped":false,"hasInlineConfig":false}!../../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./captcha.vue in ./src/components/projects/captcha.vue
* !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-82755dc4","scoped":false,"hasInlineConfig":false}!../../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./bigquery_project.vue in ./src/components/projects/bigquery_project.vue
* !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-50650498","scoped":false,"hasInlineConfig":false}!../../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./grabpustak.vue in ./src/components/projects/grabpustak.vue

To install them, you can run: npm install --save !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-3df80271","scoped":false,"hasInlineConfig":false}!../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./App.vue !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-33ec801b","scoped":false,"hasInlineConfig":false}!../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./apnav.vue !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-4d55f832","scoped":false,"hasInlineConfig":false}!../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./contact.vue !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-40cc66c3","scoped":false,"hasInlineConfig":false}!../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./projects.vue !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-15ef8928","scoped":false,"hasInlineConfig":false}!../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./home.vue !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-246589fe","scoped":false,"hasInlineConfig":false}!../../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./kisanmitra.vue !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-12704844","scoped":false,"hasInlineConfig":false}!../../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./bigquery.vue !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-26460aa9","scoped":false,"hasInlineConfig":false}!../../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./manitmoodle.vue !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-6b0a1dae","scoped":false,"hasInlineConfig":false}!../../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./captcha.vue !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-82755dc4","scoped":false,"hasInlineConfig":false}!../../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./bigquery_project.vue !!vue-style-loader!styles-loader?{"minimize":false,"sourceMap":false}!../../../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-50650498","scoped":false,"hasInlineConfig":false}!../../../node_modules/vue-loader/lib/selector?type=styles&index=0&bustCache!./grabpustak.vue
> Listening at http://localhost:8080
`

**Comment by LinusBorg** [comment]
There's nothing we can say unless we can see your project's config.

**Comment by pwrstudio** [comment]
I ran into the same problem just now, trying to update a project generated by an older version of vue-cli. It seemed `sass-loader` and `node-sass` were not installed, so this did it for me:

```
npm install sass-loader node-sass --save-dev
```

**Comment by pateash** [comment]
It comes out that it was because of some other error, not because of  **vue-loader**, 
so closing.

**Comment by Jemdo** [comment]
This message could appear when path to project contains ! (exclamation mark) in it.
Dunno if it's related to loader, still worth noting tho.

**Comment by mistresseve666** [comment]
Confirmed what @Jemdo stated. If the path of the project contains a `!`  you get the above error.
