### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by Hypnosphi** [vuejs/vue-style-loader#21]
Currently, there's no way to find out what are the breaking changes in major release

**Comment by richardtallent** [comment]
Agreed... I'm especially trying to tread lightly in upgrades right now just in case anything has a dependency for webpack 4 or doesn't work with the Vue CLI template's hot-reload, but without some details about the version change, it's hard to know if it's "safe" to upgrade yet.

**Comment by yyx990803** [comment]
closed via afe4715
