### ISSUE TITLE
Cant load styles in vue template, when shadow mode is on

### ISSUE THREAD

**Issue by rikser123** [vuejs/vue-style-loader#27]
Hello. For some part of my vue single file components I use vue-webcomponent-wrap, and in this case style loader load styles perfectly. But for usual vue templates without webcomponents-wrap I have error **""TypeError: Cannot read property '_injectedStyles' of undefined"";** 

When I switche style loader shadow mode to false, usual templates load styles, but webcomponents have error. 

is there any way to load style in both cases: for usual vue templates and for webcomponents?

**Comment by yyx990803** [comment]
This option is specifically designed to work with the wc wrapper, and should only be used during build. You will need to use different values based on whether you are using wc wrapper or not.
