### ISSUE TITLE
compatible the css-loader of new version

### ISSUE THREAD

**Issue by 8bitBelief** [vuejs/vue-style-loader#49]
the css-loader of new version use esModule default,but vue-style-loader not recognized.we should set esModule false of css-loader to use it.so,hope to update vue-style-loader

**Comment by lightyisu** [comment]
> the css-loader of new version use esModule default,but vue-style-loader not recognized.we should set esModule false of css-loader to use it.so,hope to update vue-style-loader

I have some problem When I use webpack to build a project by vue SFC.I use ['vue-style-loader','css-loader'] to handle The .css and They are The latest version.The code in <template> and <script> works good and render correctly But The code in <style> doesn' t work.and it seems The vue-style-loader doesn't work.Is that what's causing the problem?Thank YOU.

**Comment by cjblomqvist** [comment]
See #46 and #47

**Comment by 8bitBelief** [comment]
> > the css-loader of new version use esModule default,but vue-style-loader not recognized.we should set esModule false of css-loader to use it.so,hope to update vue-style-loader
> 
> I have some problem When I use webpack to build a project by vue SFC.I use ['vue-style-loader','css-loader'] to handle The .css and They are The latest version.The code in and <script> works good and render correctly But The code in <style> doesn' t work.and it seems The vue-style-loader doesn't work.Is that what's causing the problem?Thank YOU.

yes，you can ust style-loader or set the option esModule to false of css-loader

**Comment by 8bitBelief** [comment]
> See #46 and #47

**Comment by cjblomqvist** [comment]
@8bitBelief  - agree, but why aren't you merging in #47 to get rid of this problem once and for all? (I assume you have merge rights since you can close issues?)

**Comment by privatenumber** [comment]
@cjblomqvist 

I don't think he's a core member. Issue authors can close their own issues.

Best we can do is ping Vue/Evan on the PR or Twitter.

**Comment by cjblomqvist** [comment]
Ah, my bad!
