### ISSUE TITLE
Update loader-utils to v2

### ISSUE THREAD

**Issue by daniluk4000** [vuejs/vue-style-loader#60]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
loader-utils v1 has critical vulnerability that has been resolved in >=2.0.3

**If this is a feature request, what is motivation or use case for changing the behavior?**
Fix a critical dependency

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
![изображение](https://user-images.githubusercontent.com/10450717/200256781-f370a987-c805-4314-8b32-dec3d375d35a.png)

**Comment by Zae** [comment]
loader-utils v2 has actually also already been deprecated, so update to v3 immediately would be the best.

**Comment by daniluk4000** [comment]
@Zae does vue-style-loader works with Webpack 5 actually? loader-utils v3 doesn't support Webpack 4 as I could remember

**Comment by Zae** [comment]
Good question actually, I don't know. loader-utils says nothing about which versions of webpack they support, either in the changelog or in the package.json.

**Comment by daniluk4000** [comment]
Once https://github.com/webpack/loader-utils/issues/218 will be made we'll at least be able to get rid of vulnerability in v1 by updating minor deps (npm update/yarn upgrade etc)

**Comment by haoqunjiang** [comment]
https://github.com/webpack/loader-utils/issues/218#issuecomment-1306163826 Fixed in `loader-utils@1.4.1`
